<a href="https://colab.research.google.com/github/Dilmurod10/Suniy_intelekt/blob/main/Chiziqli_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [6]:
x=np.array([[1,2],[2,3],[2,1]])
x

array([[1, 2],
       [2, 3],
       [2, 1]])

In [7]:
y=np.array([[2,3,1],[12,4,6]])
y

array([[ 2,  3,  1],
       [12,  4,  6]])

In [8]:
np.dot(x,y)

array([[26, 11, 13],
       [40, 18, 20],
       [16, 10,  8]])

In [9]:
np.dot(y,x)

array([[10, 14],
       [32, 42]])