<a href="https://colab.research.google.com/github/Dilmurod10/Suniy_intelekt/blob/main/Fayllar_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save("data",arr)

In [5]:
arr2=np.load("data.npy")

In [6]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1=np.random.randn(7)

In [9]:
np.savez("arrays",a=arr,b=arr1)

In [10]:
arrays=np.load("arrays.npz")

In [11]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arrays['b']

array([ 0.79235151, -2.25083438,  0.02245062,  0.33952068, -1.37605773,
        2.12646777,  0.17379674])