<a href="https://colab.research.google.com/github/Dilmurod10/Suniy_intelekt/blob/main/Indekslash_va_kesish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
arr=np.arange(10,100,10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
arr[3:7]

array([40, 50, 60, 70])

In [7]:
arr1=arr[3:5].copy()
arr1[:]=0
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
arr2=np.array([[1,3,4],[1,2,5],[6,7,8]])
arr2

array([[1, 3, 4],
       [1, 2, 5],
       [6, 7, 8]])