<a href="https://colab.research.google.com/github/Dilmurod10/Suniy_intelekt/blob/main/Mantiqiy_shart_operatorlari.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

where funksiyasi

In [7]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])

In [5]:
cond=np.array([True,False,True,True,False])

In [9]:
result=np.where(cond,xarr,yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [12]:
arr=np.random.randn(5,2)
arr

array([[ 0.44294938, -1.95544401],
       [-0.89353781, -1.72370292],
       [ 2.06003041,  1.69631782],
       [ 1.52184727, -1.35633653],
       [-0.87044953,  0.48920202]])

In [15]:
results=np.where(arr>=0,1,-1)
results

array([[ 1, -1],
       [-1, -1],
       [ 1,  1],
       [ 1, -1],
       [-1,  1]])