<a href="https://colab.research.google.com/github/Dilmurod10/Suniy_intelekt/blob/main/Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy kutubxonasi bilan ishlash Array(massiv)

In [1]:
import numpy as np

In [2]:
data1=[1,2,3,4]  #list
arr1=np.array(data1)  #array

In [3]:
arr1

array([1, 2, 3, 4])

In [5]:
data2=(82,32,4,2)   #tuple
arr2=np.array(data2)   #array

In [6]:
arr2

array([82, 32,  4,  2])

Massiv o'lchami

In [7]:
arr1.ndim # massivning o'lchamini topish

1

Yuqori o'lchamli massivlar

In [18]:
data3=[[1,2,3,4],[3,2,5,6]]
arr3=np.array(data3)

In [19]:
arr3.ndim

2

Shape va size metodlari

shape massivning qator va ustunlarini chiqarib beradi.
Size massivning elementlar sonini chiqarib beradi.

In [20]:
arr3.shape #(qator, ustun)

(2, 4)

In [21]:
arr3.size

8

Zeros va ones metodlari

In [23]:
arr4=np.zeros(shape=(2,4))   #zeros 0 lardan iborat massiv yaratadi
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
arr5=np.ones((2,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Arange funksiyasi

In [25]:
arr6=np.arange(1,29,4)
arr6

array([ 1,  5,  9, 13, 17, 21, 25])

In [26]:
arr7=np.arange(26)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])