<a href="https://colab.research.google.com/github/Dilmurod10/Suniy_intelekt/blob/main/Sorting_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.random.rand(4)

In [3]:
arr.sort()
arr

array([0.42863943, 0.46226066, 0.47319896, 0.91380572])

In [4]:
arr2=-np.sort(-arr)
arr2

array([0.91380572, 0.47319896, 0.46226066, 0.42863943])

In [6]:
arr3=np.random.randn(4,3)
arr3

array([[ 0.20834512,  0.54872874, -2.53175802],
       [-0.53555166,  0.71017707, -1.2934396 ],
       [-0.63426004, -0.99634084,  0.51964367],
       [ 0.59210526, -2.44784154, -0.52996114]])

In [7]:
row_arr=np.sort(arr3,axis=0)
row_arr

array([[-0.63426004, -2.44784154, -2.53175802],
       [-0.53555166, -0.99634084, -1.2934396 ],
       [ 0.20834512,  0.54872874, -0.52996114],
       [ 0.59210526,  0.71017707,  0.51964367]])

In [8]:
low_arr=np.sort(arr3,axis=1)
low_arr

array([[-2.53175802,  0.20834512,  0.54872874],
       [-1.2934396 , -0.53555166,  0.71017707],
       [-0.99634084, -0.63426004,  0.51964367],
       [-2.44784154, -0.52996114,  0.59210526]])