<a href="https://colab.research.google.com/github/Dilmurod10/Suniy_intelekt/blob/main/Universal_funksiyalar_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Universal funksiyalar

sqrt, square, exp,log, modf, sign, isnan funksiyalarini ko'rib chiqamiz


 Unary funksiyalar(bitta argument qabul qiluvchi funksiyalar)

In [3]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

*modf* bu funksiya massiv elementlarining butun va qoldiq qismlarini ajratib beradi

In [11]:
arr1=np.random.randn(6)
arr1

array([-1.66886567, -0.77084849,  0.9826036 ,  0.22892561, -0.65807864,
        0.84798641])

In [12]:
qoldiq,butun=np.modf(arr1)

In [13]:
print(qoldiq)
print(butun)

[-0.66886567 -0.77084849  0.9826036   0.22892561 -0.65807864  0.84798641]
[-1. -0.  0.  0. -0.  0.]


**sign** funksiyasi massiv elementlari mafiy bo'lsa -1 aks holda 1 qiymat qaytaradi

In [24]:
np.sign(arr1)

array([nan, -1.,  1.,  1., -1.,  1.])

*isnan* funksiyasi massivda nan bor yo'qligini tekshiradi

In [25]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

In [23]:
np.abs(arr1)

array([       nan, 0.77084849, 0.9826036 , 0.22892561, 0.65807864,
       0.84798641])

In [26]:
arr1[0]=0.1

In [29]:
np.ceil(arr1)

array([ 1., -0.,  1.,  1., -0.,  1.])

In [30]:
np.rint(arr1)

array([ 0., -1.,  1.,  0., -1.,  1.])

In [31]:
arr1

array([ 0.1       , -0.77084849,  0.9826036 ,  0.22892561, -0.65807864,
        0.84798641])

Binary (2 ta argument qabul qiluvchi )funksiyalar
add, multiply, maximum funksiyalarini ko'rib chiqamiz

add 2ta massivni bir biriga qo'shish

In [32]:
arr2=np.random.randn(7)
arr3=np.random.randn(7)

In [33]:
np.add(arr2,arr3)

array([ 0.03266395,  2.40646237,  0.60016705,  2.89617724,  0.75835551,
       -1.04563094,  0.2994287 ])

In [34]:
arr2+arr3

array([ 0.03266395,  2.40646237,  0.60016705,  2.89617724,  0.75835551,
       -1.04563094,  0.2994287 ])

multiply massivni massivga ko'paytirish

In [35]:
np.multiply(arr2,arr3)

array([-0.01708094,  1.44715595,  0.07566758,  1.30844575, -0.62707498,
       -0.02352883, -0.91033314])

In [36]:
arr2*arr3

array([-0.01708094,  1.44715595,  0.07566758,  1.30844575, -0.62707498,
       -0.02352883, -0.91033314])

In [37]:
np.maximum(arr2,arr3)

array([0.14804255, 1.22791604, 0.42001077, 2.33607223, 1.25715882,
       0.02203758, 1.1155029 ])